/* Generated by scripts/build-site-smart-search.js — do not edit by hand */
(function (global) {
const SYNONYM_GROUPS = [
  // RP-термины
  ['nonrp', 'non rp', 'non-rp', 'нонрп', 'нон рп', 'не рп', 'нерп'],
  ['powergaming', 'power gaming', 'повергейминг', 'пг', 'pg'],
  ['metagaming', 'meta gaming', 'метагейминг', 'мг', 'mg'],
  ['deathmatch', 'death match', 'дефматч', 'дм', 'dm'],
  ['revenge kill', 'revengekill', 'реванш', 'рк', 'rk'],
  ['team kill', 'teamkill', 'тимкилл', 'тк', 'tk'],
  ['spawn kill', 'spawnkill', 'спавнкилл', 'ск', 'sk'],
  ['failrp', 'fail rp', 'фейлрп', 'фейл рп'],
  ['bug abuse', 'багоюз', 'багабуз', 'абуз'],
  ['rdm', 'random deathmatch', 'рандомный дм'],

  // Убийство и насилие
  ['убийство', 'убил', 'убила', 'убили', 'убить', 'убийца', 'зарезал', 'застрелил', 'пристрелил', 'зарубил', 'заколол'],
  ['лишение жизни', 'причинение смерти', 'смерть', 'смертельный', 'летальный'],
  ['избиение', 'избил', 'избили', 'побои', 'побил', 'избивать', 'драка'],
  ['насилие', 'насильственный', 'применение силы'],
  ['разбой', 'разбойник', 'разбойное', 'нападение', 'напал', 'напали', 'напасть'],
  ['хулиганство', 'хулиган', 'хулиганить'],
  ['похищение', 'похитил', 'похитили', 'похищать', 'захват', 'захватил', 'заложник'],
  ['пытки', 'пытка', 'пытать', 'истязание'],

  // Кражи и имущество
  ['кража', 'украл', 'украли', 'украсть', 'воровство', 'вор', 'стырил', 'стырить'],
  ['хищение', 'хищения', 'присвоение', 'присвоил'],
  ['грабеж', 'ограбление', 'ограбил', 'ограбили', 'ограбить', 'грабитель', 'отобрал'],
  ['мошенничество', 'мошенник', 'обман', 'обманул', 'скам', 'scam'],
  ['вымогательство', 'вымогал', 'вымогать', 'вымогатель'],
  ['вандализм', 'вандал', 'поломал', 'сломал', 'разрушил', 'повредил'],
  ['угон', 'угнал', 'угнали', 'угонщик', 'угнан', 'угонять', 'угнанный'],

  // Оружие и наркотики
  ['оружие', 'оружия', 'ствол', 'пушка', 'огнестрел', 'огнестрельное', 'пистолет', 'автомат', 'винтовка'],
  ['холодное оружие', 'нож', 'ножом', 'кастет', 'бита'],
  ['наркотики', 'наркотик', 'наркота', 'дурь', 'закладка', 'закладки', 'распространение', 'сбыт', 'торговля наркотиками'],
  ['алкоголь', 'пьянство', 'пьян', 'опьянение', 'нетрезвый', 'выпивший'],

  // Дорога и транспорт
  ['пдд', 'дорожное движение', 'правила дорожного'],
  ['скорость', 'превышение скорости', 'быстро ехал', 'гонка', 'погоня', 'уличные гонки', 'драг'],
  ['дтп', 'авария', 'столкновение', 'врезался', 'сбил', 'наезд'],
  ['парковка', 'припаркован', 'неправильная парковка', 'стоянка'],
  ['водитель', 'вождение', 'управление транспортом', 'за рулем'],

  // КоАП гл. IX — сплошная / встречка / разметка
  [
    'сплошная', 'сплошную', 'сплошной', 'двойная сплошная', 'сплошная линия',
    'встречка', 'на встречку', 'выезд на встречку', 'встречная', 'встречную',
    'встречное', 'встречного', 'встречная полоса', 'встречное движение',
    'полоса встречного', 'полоса встречного движения',
    'движение по встречке', 'выезд на встречную',
  ],
  ['обгон', 'обогнал', 'обгонять', 'запрещённый обгон', 'запрещенный обгон'],
  ['красный', 'на красный', 'проезд на красный', 'светофор', 'стоп линия', 'стоп-линия'],
  ['тонировка', 'тонированный', 'тонировка стекол', 'затонирован'],
  ['опьянение', 'пьяный за рулем', 'пьяный за рулём', 'нетрезвый водитель', 'алкоголь за рулем'],
  ['опасное вождение', 'агрессивное вождение', 'шашки'],
  ['превышение', 'превысил скорость', 'спидометр', 'киллометраж'],
  ['обочина', 'по обочине', 'разделительная полоса'],
  ['дистанция', 'интервал', 'не соблюдал дистанцию'],
  ['пешеходный переход', 'зебра', 'пешеход', 'не пропустил пешехода'],
  ['маячки', 'проблесковый', 'мигалки', 'сирена'],
  ['знаки', 'дорожные знаки', 'разметка', 'игнорирование знаков'],

  // УК — вред здоровью
  [
    'тяжкий вред', 'тяжкого вреда', 'тяжкому вреду', 'тяжкий', 'тяжкого',
    'тяжелый вред', 'тяжелого вреда', 'причинение тяжкого вреда',
    'тяжкого вреда здоровью', 'причинение тяжкого вреда здоровью',
  ],
  [
    'средний вред', 'средней тяжести', 'вред средней тяжести',
    'причинение вреда средней тяжести',
  ],
  [
    'легкий вред', 'лёгкий вред', 'легкого вреда', 'лёгкого вреда',
    'причинение легкого вреда', 'причинение лёгкого вреда',
  ],
  ['вред здоровью', 'вреда здоровью', 'вреду здоровью', 'причинение вреда здоровью'],

  // Полиция и госструктуры
  ['полиция', 'полицейский', 'коп', 'копы', 'мент', 'менты', 'правоохранитель', 'легавый', 'легавые'],
  ['фсб', 'фсин', 'прокуратура', 'следователь', 'следствие', 'дознание'],
  ['арест', 'арестовал', 'арестован', 'задержание', 'задержал', 'задержан', 'наручники'],
  ['обыск', 'обыскал', 'обыскивать', 'конфискация', 'конфисковал'],
  ['штраф', 'штрафовать', 'оштрафовать', 'взыскание'],
  ['лишение прав', 'лишение водительских', 'лишили прав'],
  ['тюрьма', 'тюремный', 'заключение', 'лишение свободы', 'срок', 'кпз', 'сизо'],

  // Коррупция и должностные
  ['коррупция', 'взятка', 'взяточничество', 'откат', 'подкуп', 'подкупил'],
  ['должностное', 'служебное', 'злоупотребление', 'превышение полномочий'],
  ['халатность', 'неисполнение', 'бездействие'],

  // Оскорбления и дискриминация
  ['оскорбление', 'оскорбил', 'оскорблять', 'обзывать', 'обозвал', 'нецензурная'],
  ['клевета', 'дискредитация', 'дискриминация', 'унижение', 'унизил'],
  ['травля', 'буллинг', 'булинг', 'токсичность', 'токсик'],

  // Территории и зоны
  ['закрытая территория', 'зт', 'закрытая зона', 'закрытый объект'],
  ['государственная', 'гос', 'госструктура', 'госорган'],
  ['военная', 'военный', 'военкомат', 'армия', 'вооруженные силы'],

  // Прочее RP
  ['респаун', 'респ', 'respawn', 'возрождение'],
  ['чат', 'оскорбление в чате', 'флуд', 'спам', 'спамить', 'флудить'],
  ['мат', 'маты', 'матерщина', 'нецензурная лексика'],
  ['реклама', 'рекламировать', 'промо', 'промокод'],
  ['музыка', 'музыкальный', 'music abuse', 'музыкаабуз'],
  ['телепорт', 'телепортация', 'тп', 'tp'],
  ['чит', 'читы', 'читер', 'cheat', 'читерство'],
  ['эвакуация', 'эвакуировал', 'эвакуатор'],
  ['лицензия', 'лицензии', 'разрешение', 'удостоверение'],
  ['суд', 'судебный', 'судья', 'приговор', 'иск'],
  ['свидетель', 'показания', 'давать показания'],
  ['самооборона', 'защита', 'оборона'],
  ['экстренный', 'экстренная ситуация', 'чп'],
];

function normalizeKey(value) {
  return String(value || '')
    .toLowerCase()
    .replace(/ё/g, 'е')
    .replace(/\s+/g, ' ')
    .trim();
}

function buildSynonymMap(groups) {
  const map = new Map();

  for (const group of groups) {
    const normalized = [...new Set(group.map(normalizeKey).filter(Boolean))];
    for (const term of normalized) {
      const existing = map.get(term) || new Set();
      for (const alt of normalized) {
        if (alt !== term) existing.add(alt);
      }
      map.set(term, existing);
    }
  }

  return map;
}

const SYNONYM_MAP = buildSynonymMap(SYNONYM_GROUPS);

function expandTerm(term) {
  const key = normalizeKey(term);
  if (!key) return [];

  const result = new Set([key]);
  const synonyms = SYNONYM_MAP.get(key);
  if (synonyms) {
    for (const alt of synonyms) result.add(alt);
  }
  return [...result];
}

function expandQueryTerms(query) {
  const words = normalizeKey(query)
    .replace(/[^а-яa-z0-9\s-]/gi, ' ')
    .split(/\s+/)
    .filter((w) => w.length >= 2);

  const terms = new Set();
  const full = normalizeKey(query);
  if (full.length >= 2) terms.add(full);

  for (const word of words) {
    for (const term of expandTerm(word)) terms.add(term);
  }

  return [...terms].sort((a, b) => b.length - a.length);
}



const STOP_WORDS = new Set([
  'как', 'что', 'кто', 'где', 'когда', 'какой', 'какие', 'какая', 'какое',
  'это', 'для', 'при', 'без', 'или', 'если', 'будет', 'можно', 'нужно',
  'должен', 'может', 'его', 'ее', 'их', 'они', 'она', 'оно', 'этот', 'эта',
  'все', 'всё', 'также', 'быть', 'был', 'была', 'были', 'есть', 'нет', 'уже',
  'ещё', 'еще', 'так', 'тоже', 'очень', 'после', 'перед', 'через',
  'между', 'под', 'над', 'вот', 'чем', 'том', 'того', 'ли', 'бы', 'же',
  'the', 'and', 'for', 'with', 'from',
]);

const EN_TO_RU = {
  q: 'й', w: 'ц', e: 'у', r: 'к', t: 'е', y: 'н', u: 'г', i: 'ш', o: 'щ', p: 'з',
  '[': 'х', ']': 'ъ', a: 'ф', s: 'ы', d: 'в', f: 'а', g: 'п', h: 'р', j: 'о', k: 'л',
  l: 'д', ';': 'ж', "'": 'э', z: 'я', x: 'ч', c: 'с', v: 'м', b: 'и', n: 'т', m: 'ь',
  ',': 'б', '.': 'ю', '/': '.', '`': 'ё',
};

function enToRu(str) {
  return String(str).split('').map((ch) => {
    const lower = ch.toLowerCase();
    const mapped = EN_TO_RU[lower];
    if (!mapped) return ch;
    return ch === lower ? mapped : mapped.toUpperCase();
  }).join('');
}

function getQueryVariants(query) {
  const trimmed = String(query || '').trim();
  if (!trimmed) return [];
  const variants = [trimmed];
  if (/[a-z]/i.test(trimmed)) {
    const ru = enToRu(trimmed);
    if (ru !== trimmed) variants.push(ru);
  }
  return variants;
}

function tokenizeQuery(query) {
  return normalizeKey(query)
    .replace(/[^а-яa-z0-9\s-]/gi, ' ')
    .split(/\s+/)
    .filter((w) => w.length >= 2 && !STOP_WORDS.has(w));
}

function getSearchTermsForWord(word) {
  const normalized = normalizeKey(word);
  const terms = expandTerm(word);
  if (normalized.length <= 3 && terms.length > 1) return terms;
  return terms.filter((term) => term === normalized || term.length >= 5);
}

function getWordGroups(query) {
  return tokenizeQuery(query).map(getSearchTermsForWord);
}

function buildSearchText(item) {
  const body = [];
  const punishment = [];
  for (const part of item.parts || []) {
    if (part.text) body.push(part.text);
    if (part.punishment) punishment.push(part.punishment);
  }
  return normalizeKey([
    item.articleNumber,
    item.title,
    item.chapter,
    item.section,
    item.code,
    item.preview,
    item.searchText,
    (item.keywords || []).join(' '),
    punishment.join(' '),
    item.fullText,
    body.join(' '),
  ].join(' '));
}

function isTokenChar(ch) {
  return /[a-zа-яё0-9]/i.test(ch);
}

function requiresWordBoundary(term) {
  return normalizeKey(term).length <= 3;
}

function findTermIndex(haystack, term, wordBoundary = null) {
  const normalizedHaystack = normalizeKey(haystack);
  const normalizedTerm = normalizeKey(term);
  if (!normalizedTerm) return -1;

  const useBoundary = wordBoundary ?? requiresWordBoundary(normalizedTerm);
  let idx = 0;

  while (idx <= normalizedHaystack.length - normalizedTerm.length) {
    const pos = normalizedHaystack.indexOf(normalizedTerm, idx);
    if (pos === -1) return -1;

    if (!useBoundary) return pos;

    const before = pos > 0 ? normalizedHaystack[pos - 1] : '';
    const after =
      pos + normalizedTerm.length < normalizedHaystack.length
        ? normalizedHaystack[pos + normalizedTerm.length]
        : '';

    if ((!before || !isTokenChar(before)) && (!after || !isTokenChar(after))) {
      return pos;
    }

    idx = pos + 1;
  }

  return -1;
}

/** Как в приложении: короткие термины только по границам слова (иначе «дм» ловит «администрацией»). */
function containsTerm(haystack, term) {
  const t = normalizeKey(term);
  if (!t || t.length < 2) return false;
  if (requiresWordBoundary(t)) {
    return findTermIndex(haystack, t, true) !== -1;
  }
  return haystack.includes(t);
}

function matchesWordGroups(haystack, wordGroups) {
  if (!wordGroups.length) return false;
  const minRequired = wordGroups.length === 1 ? 1 : Math.ceil(wordGroups.length * 0.6);
  let matched = 0;
  for (const group of wordGroups) {
    if (group.some((term) => containsTerm(haystack, term))) matched += 1;
  }
  return matched >= minRequired;
}

function isShortAcronymQuery(rawQuery) {
  for (const variant of getQueryVariants(rawQuery)) {
    const full = normalizeKey(variant);
    if (full.length > 0 && full.length <= 3) return true;
    for (const word of tokenizeQuery(variant)) {
      if (word.length <= 3) return true;
    }
  }
  return false;
}

function codeSearchPriority(item) {
  const code = String(item?.code || '').toUpperCase().replace(/Ё/g, 'Е');
  const key = String(item?.lawKey || '').toUpperCase();
  if (key === 'KOAP' || code === 'КОАП' || code === 'KOAP') return 0;
  if (key === 'UK' || code === 'УК' || code === 'UK') return 0;
  return 1;
}

function search(items, rawQuery) {
  const variants = getQueryVariants(rawQuery);
  if (!variants.length) return items.slice();

  const scored = new Map();
  const add = (item, score) => {
    const key = item.id || `${item.code}::${item.articleNumber}`;
    const prev = scored.get(key);
    if (!prev || score < prev.score) scored.set(key, { item, score });
  };

  for (const variant of variants) {
    const full = normalizeKey(variant);
    const wordGroups = getWordGroups(variant);

    for (const item of items) {
      const hay = buildSearchText(item);
      if (full.length >= 2 && containsTerm(hay, full)) {
        add(item, 0);
        continue;
      }
      if (wordGroups.length && matchesWordGroups(hay, wordGroups)) {
        add(item, 1);
      }
    }
  }

  // Короткие аббревиатуры (дм, пг, рк…) — без Fuse, иначе мусор по подстрокам
  if (scored.size === 0 && !isShortAcronymQuery(rawQuery) && typeof Fuse !== 'undefined') {
    const fuse = new Fuse(items, {
      keys: [
        { name: 'articleNumber', weight: 3 },
        { name: 'title', weight: 2 },
        { name: 'code', weight: 2 },
        { name: 'keywords', weight: 2 },
        { name: 'parts.text', weight: 1 },
        { name: 'parts.punishment', weight: 1.5 },
      ],
      threshold: 0.35,
      ignoreLocation: true,
      includeScore: true,
    });
    for (const r of fuse.search(String(rawQuery).trim(), { limit: 60 })) {
      add(r.item, 2 + (r.score || 0));
    }
  }

  return [...scored.values()]
    .sort((a, b) => (
      codeSearchPriority(a.item) - codeSearchPriority(b.item)
      || a.score - b.score
    ))
    .map((e) => e.item);
}

function getHighlightTerms(query) {
  if (!String(query || '').trim()) return [];

  const terms = new Set();

  for (const variant of getQueryVariants(query)) {
    const full = normalizeKey(variant);
    if (full.length >= 2) terms.add(full);

    for (const word of tokenizeQuery(variant)) {
      for (const term of getSearchTermsForWord(word)) {
        const normalized = normalizeKey(term);
        if (normalized.length >= 2) terms.add(normalized);
      }
    }
  }

  return [...terms].sort((a, b) => b.length - a.length);
}

global.SiteSmartSearch = {
  search,
  expandTerm,
  normalizeKey,
  getHighlightTerms,
  findTermIndex,
};
})(typeof window !== 'undefined' ? window : global);
